-- AlterTable
ALTER TABLE `manufacturer` ADD COLUMN `dailyCodeLimit` INTEGER NOT NULL DEFAULT 50,
    ADD COLUMN `plan` ENUM('BASIC', 'PREMIUM') NOT NULL DEFAULT 'BASIC',
    ADD COLUMN `planExpiresAt` DATETIME(3) NULL;

-- AlterTable
ALTER TABLE `user` ADD COLUMN `dailyCodeLimit` INTEGER NOT NULL DEFAULT 50,
    ADD COLUMN `plan` ENUM('BASIC', 'PREMIUM') NOT NULL DEFAULT 'BASIC',
    ADD COLUMN `planExpiresAt` DATETIME(3) NULL;
